#!/usr/bin/env python3
from python_starter.structs import Dog

if __name__ == "__main__":
    dog = Dog("tmp", "tmp")
    print(f"\n[INFO] Dog is good!\n" if dog.is_good() else "\n[INFO] Dog is doog!\n")
